POST http://localhost:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=tom
&password=password

###
POST http://localhost:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=Pam
&password=123pam

###
POST http://localhost:8000/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQYW0iLCJleHAiOjE3MjAyNDY4OTEsIm1vZGUiOiJyZWZyZXNoX3Rva2VuIn0.5deraU2xwcUCjYg-MS_b5rNaywyrD2GkkTaqj9fdyZM

###
GET http://localhost:8000/api/v1/auth/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQYW0iLCJleHAiOjE3MTk2NDIxODEsIm1vZGUiOiJhY2Nlc3NfdG9rZW4ifQ.R0-8MRdOVRoY0qxqbQ1xeRXCmhrkc5VSLN86nG6pbx4