POST http://localhost:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=christianbueno.1@gmail.com
&password=maGazine1!

###
POST http://143.198.27.14:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=christianbueno.1@gmail.com
&password=maGazine1!

###
POST http://localhost:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=bruce123
&password=hello1!A

###
POST http://localhost:8000/api/v1/auth/token
Content-Type: application/x-www-form-urlencoded

username=pam@ibm.com
&password=pam123

###
POST http://localhost:8000/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjaHJpc3RpYW5idWVuby4xQGdtYWlsLmNvbSIsImV4cCI6MTc0MTc0NDEyMiwibW9kZSI6InJlZnJlc2hfdG9rZW4ifQ.Fmr4AHZ7KHDLOXS7gv3b3Qbcfp6UCgPw7DyQatvZDp4

###
GET http://localhost:8000/api/v1/auth/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjaHJpc3RpYW5idWVuby4xQGdtYWlsLmNvbSIsImV4cCI6MTc0MTY1Nzk5NiwibW9kZSI6ImFjY2Vzc190b2tlbiJ9.9R4sicYkSembw-ZvPRMeRqcqsPx7ArBicVmeaYG_vZU

###
# register a new user
POST http://localhost:8000/api/v1/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjaHJpc3RpYW5idWVuby4xQGdtYWlsLmNvbSIsImV4cCI6MTc0MTY1Nzk5NiwibW9kZSI6ImFjY2Vzc190b2tlbiJ9.9R4sicYkSembw-ZvPRMeRqcqsPx7ArBicVmeaYG_vZU
Content-Type: application/json

{
    "username": "chris123",
    "email": "chris123@ibm.com",
    "password": "maGazine1!",
    "disabled": false,
    "role": "user"
}

###
# register a new user
POST http://localhost:8000/api/v1/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjaHJpc3RpYW5idWVuby4xQGdtYWlsLmNvbSIsImV4cCI6MTc0MTc0MjkxNSwibW9kZSI6InJlZnJlc2hfdG9rZW4ifQ.Vw3XCgjppBfV0F46LxHDPKMQB85iXsHuXXGqTclKd9U
Content-Type: application/json

{
    "username": "tim123",
    "email": "tim@foo.xyz",
    "password": "maGazine1!",
    "disabled": false,
    "role": "user"
}

###
# clear-tokens
POST http://localhost:8000/api/v1/auth/clear-tokens
Authorization

###
# signup, self-register
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "username": "bruce1234",
    "email": "bruce123@ibm.com",
    "password": "hello1!A",
    "disabled": false,
    "role": "user"
}